### ISSUE TITLE
A question about the data dependency graph

### ISSUE THREAD

**Issue by ITWOI** [ghaffarian/progex#16]
Hi,

Thank you for your work.
May I ask why the generated data dependence graph contains control flow edges?

Thanks for your time.

**Comment by ghaffarian** [comment]
This is related to the algorithm used for extracting data-dependence relations. The algorithm used in PROGEX first performs DEF-USE analysis, which specifies which variables are defined or used in every statement of the program. Then it traverses the program's CFG and utilizes the gathered DEF-USE information in order to extract data-dependence relations among statements.

Other than this, the CFG is also used in the visualization phase to present a more comprehensible graph for the human user.

If you only intend to consume the DDG graph via machine/programs, you can easily ignore the CFG and only traverse the DDG edges.

**Comment by ITWOI** [comment]
Thanks for your answer.
Ignoring the CFG is easy but I'm just curious about your design.
Your work does help me a lot.
Thanks again.
