### ISSUE TITLE
Problem Following the Usage-Guide and Building from Source

### ISSUE THREAD

**Issue by shazhendong** [ghaffarian/progex#8]
I'm trying to use progex, I'm having trouble following your usage guide, would you mind explaining how to setup everything in more details?

how do i get the `progex.jar` for `java -jar PROGEX.jar /path/to/program/src`

**Comment by shazhendong** [comment]
‘mvn install’ can not built the the program. It always ended up with:

> [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.106 s
[INFO] Finished at: 2019-09-24T23:38:26-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project javacg: There are test failures.

**Comment by ghaffarian** [comment]
If you only want to use PROGEX there is no need to build from source. You can simply refer to the [releases page](https://github.com/ghaffarian/progex/releases), download the latest stable release and you can find the `progex.jar` file and all its dependencies in order to test run the tool.

**Comment by ghaffarian** [comment]
If you want to modify and develop your own changes, then here are the steps:

1. First clone the following two repos and do `mvn install` in each project:
  - https://github.com/ghaffarian/nanologger
  - https://github.com/ghaffarian/graphs
2. Now you can do `mvn compile` in PROGEX. But you still can't run the unit-tests.
3. In order to run the unit-tests and do a full `mvn install` cycle, you need to create two directories:
  - `src/test/resources/java/benchmark-v1.2/`
  - `src/test/resources/java/juliet-v1.3/`

  4. After creating the above directories you can do a full `mvn clean install` of the project.

**Comment by shazhendong** [comment]
Thank you!

**Comment by ghaffarian** [comment]
I just released PROGEX-v3.4.0 with several improvements.
The requirement to create some directories to pass the unit-tests is now removed 
and developer's guide is now added to the README.

**Comment by shazhendong** [comment]
Excellent! Thank you!
